version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=rootuser
      - DB_NAME=chatapp_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - chat-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootuser
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres-data:
