version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build: ./backend
    environment:
      - DB_HOST=postgres
      - DB_USER=root
      - DB_PASSWORD=rootuser
      - DB_NAME=chatapp_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - chat-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootuser
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-network

# Uncomment to use pgadmin to be able to connect and manage the postgres database from browser
#  pgadmin:
#    image: dpage/pgadmin4
#    depends_on:
#      - postgres
#    ports:
#      - "5050:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: root@root.com
#      PGADMIN_DEFAULT_PASSWORD: rootuser
#    restart: unless-stopped
#    networks:
#      - chat-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: rootuser
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge

volumes:
  postgres-data:
